import type {
  AuditEvent,
  CredentialProfile,
  FaqItem,
  LeaveRequest,
  MissionAlert,
  PersonnelMember,
  PolicyWindow,
  ReadinessMetric,
  ReportSeries,
  SecurityControl,
} from "@/lib/types";

export const DEMO_ACCOUNTS: CredentialProfile[] = [
  {
    id: "u-201",
    name: "SSG Elena Ward",
    rank: "SSG",
    email: "elena.ward@army.demo",
    unit: "Alpha Company, 2-327 INF",
    role: "supervisor",
    callsign: "Atlas 6",
    missionDesk: "Company Operations",
    clearance: "SECRET",
    homeStation: "Fort Campbell, KY",
    leaveBalance: { annual: 21, sick: 9, admin: 2 },
    password: "Command!2026",
  },
  {
    id: "u-118",
    name: "SPC Maria Daniels",
    rank: "SPC",
    email: "maria.daniels@army.demo",
    unit: "Alpha Company, 2-327 INF",
    role: "soldier",
    callsign: "Atlas 2-4",
    missionDesk: "Weapons Squad",
    clearance: "SECRET",
    homeStation: "Fort Campbell, KY",
    leaveBalance: { annual: 16, sick: 7, admin: 1 },
    password: "Ranger!2026",
  },
  {
    id: "u-032",
    name: "MAJ Marcus Hale",
    rank: "MAJ",
    email: "marcus.hale@army.demo",
    unit: "Task Force Bastion",
    role: "commander",
    callsign: "Bastion 6",
    missionDesk: "Battalion Command Group",
    clearance: "TOP SECRET",
    homeStation: "Fort Liberty, NC",
    leaveBalance: { annual: 24, sick: 11, admin: 3 },
    password: "Summit!2026",
  },
];

export const READINESS_METRICS: ReadinessMetric[] = [
  {
    id: "coverage",
    label: "Unit Coverage",
    value: "87%",
    numericValue: 87,
    target: 92,
    delta: "-3 pts",
    detail: "Two squads are below ideal staffing during the next 14-day window.",
    tone: "watch",
  },
  {
    id: "sla",
    label: "Approval SLA",
    value: "6.2h",
    numericValue: 78,
    target: 85,
    delta: "+18%",
    detail: "Median turnaround improved after command-routing changes last week.",
    tone: "neutral",
  },
  {
    id: "compliance",
    label: "Policy Compliance",
    value: "98.4%",
    numericValue: 98,
    target: 95,
    delta: "+2 pts",
    detail: "Missing emergency contacts and handoff notes are down materially.",
    tone: "neutral",
  },
  {
    id: "risk",
    label: "Schedule Risk",
    value: "Moderate",
    numericValue: 62,
    target: 35,
    delta: "+4 briefs",
    detail: "Holiday overlap and gunnery prep are driving elevated command scrutiny.",
    tone: "elevated",
  },
];

export const MISSION_ALERTS: MissionAlert[] = [
  {
    id: "a-1",
    label: "Today",
    title: "Red-cycle staffing gap detected in Bravo squad",
    summary: "Two pending leave requests overlap the same machine gun team during range prep week.",
    timestamp: "06:20",
    tone: "critical",
    action: "Route for company-level review",
  },
  {
    id: "a-2",
    label: "Upcoming",
    title: "Command brief packet due before 1700",
    summary: "Readiness snapshot and leave forecast need to be exported for the battalion sync.",
    timestamp: "11:45",
    tone: "watch",
    action: "Generate command brief",
  },
  {
    id: "a-3",
    label: "Resolved",
    title: "Emergency leave package cleared without coverage loss",
    summary: "Cross-attachment plan closed the gap before the platoon support rehearsal.",
    timestamp: "Yesterday",
    tone: "neutral",
    action: "Archive to case notes",
  },
];

export const POLICY_WINDOWS: PolicyWindow[] = [
  {
    id: "p-1",
    label: "Range Density Window",
    startDate: "2026-04-22",
    endDate: "2026-04-28",
    impact: "Approvals need platoon coverage confirmation before routing.",
  },
  {
    id: "p-2",
    label: "Block Leave Freeze",
    startDate: "2026-05-12",
    endDate: "2026-05-18",
    impact: "Company commander review is mandatory for all discretionary leave.",
  },
  {
    id: "p-3",
    label: "Medical Surge Coverage",
    startDate: "2026-06-03",
    endDate: "2026-06-07",
    impact: "Medic and CLS-certified personnel requests trigger elevated risk scoring.",
  },
];

export const LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: "lr-1042",
    soldierName: "SPC Maria Daniels",
    soldierRank: "SPC",
    leaveType: "Annual Leave",
    startDate: "2026-04-24",
    endDate: "2026-04-29",
    days: 6,
    status: "pending",
    submittedDate: "2026-04-14",
    supervisor: "SSG Elena Ward",
    justification: "Sister's graduation and family travel support.",
    risk: "watch",
    missionImpact: "Overlaps range density window and reduces weapons squad depth to 83%.",
    coveragePlan: "Cross-level PFC Bishop from third team for two live-fire days.",
  },
  {
    id: "lr-1045",
    soldierName: "PFC Isaiah Brooks",
    soldierRank: "PFC",
    leaveType: "Emergency Leave",
    startDate: "2026-04-19",
    endDate: "2026-04-23",
    days: 5,
    status: "pending",
    submittedDate: "2026-04-15",
    supervisor: "SSG Elena Ward",
    justification: "Immediate family medical emergency.",
    risk: "neutral",
    missionImpact: "Manageable if battalion aide slot stays green.",
    coveragePlan: "Medic float already assigned from support platoon.",
  },
  {
    id: "lr-1028",
    soldierName: "CPL Nathan Cole",
    soldierRank: "CPL",
    leaveType: "Pass",
    startDate: "2026-04-17",
    endDate: "2026-04-18",
    days: 2,
    status: "approved",
    submittedDate: "2026-04-10",
    supervisor: "SSG Elena Ward",
    justification: "Local family event.",
    risk: "neutral",
    missionImpact: "No readiness impact.",
    coveragePlan: "None required.",
  },
  {
    id: "lr-1009",
    soldierName: "SPC Talia Mercer",
    soldierRank: "SPC",
    leaveType: "Annual Leave",
    startDate: "2026-05-13",
    endDate: "2026-05-17",
    days: 5,
    status: "denied",
    submittedDate: "2026-04-09",
    supervisor: "SSG Elena Ward",
    justification: "Out-of-state travel.",
    risk: "critical",
    missionImpact: "Conflicted directly with block leave freeze and weapons qualification support.",
    coveragePlan: "No viable relief identified.",
  },
];

export const PERSONNEL_ROSTER: PersonnelMember[] = [
  {
    id: "p-101",
    name: "SSG Elena Ward",
    rank: "SSG",
    roleTitle: "Squad Leader",
    unit: "Alpha Company, 2-327 INF",
    squad: "1st Squad",
    specialty: "11B Infantry",
    email: "elena.ward@army.demo",
    phone: "(270) 555-0141",
    location: "Fort Campbell",
    readiness: 96,
    status: "available",
    nextAvailability: "Available now",
  },
  {
    id: "p-102",
    name: "SPC Maria Daniels",
    rank: "SPC",
    roleTitle: "Weapons Team Lead",
    unit: "Alpha Company, 2-327 INF",
    squad: "Weapons Squad",
    specialty: "M240B / Range Coach",
    email: "maria.daniels@army.demo",
    phone: "(270) 555-0118",
    location: "Fort Campbell",
    readiness: 92,
    status: "available",
    nextAvailability: "Available now",
  },
  {
    id: "p-103",
    name: "PFC Isaiah Brooks",
    rank: "PFC",
    roleTitle: "Combat Medic",
    unit: "Alpha Company, 2-327 INF",
    squad: "HQ Section",
    specialty: "68W Medic",
    email: "isaiah.brooks@army.demo",
    phone: "(270) 555-0188",
    location: "Fort Campbell",
    readiness: 88,
    status: "on_leave",
    nextAvailability: "Returns Apr 24",
  },
  {
    id: "p-104",
    name: "CPL Nathan Cole",
    rank: "CPL",
    roleTitle: "Fire Team Leader",
    unit: "Alpha Company, 2-327 INF",
    squad: "2nd Squad",
    specialty: "Breacher / Assault",
    email: "nathan.cole@army.demo",
    phone: "(270) 555-0194",
    location: "Fort Campbell",
    readiness: 94,
    status: "tdy",
    nextAvailability: "Returns Apr 19",
  },
  {
    id: "p-105",
    name: "SPC Talia Mercer",
    rank: "SPC",
    roleTitle: "Signals Specialist",
    unit: "Alpha Company, 2-327 INF",
    squad: "HQ Section",
    specialty: "RTO / SATCOM",
    email: "talia.mercer@army.demo",
    phone: "(270) 555-0135",
    location: "Fort Campbell",
    readiness: 85,
    status: "training",
    nextAvailability: "Returns Apr 21",
  },
  {
    id: "p-106",
    name: "PFC Julian Bishop",
    rank: "PFC",
    roleTitle: "Automatic Rifleman",
    unit: "Alpha Company, 2-327 INF",
    squad: "3rd Squad",
    specialty: "M249 / Assistant AG",
    email: "julian.bishop@army.demo",
    phone: "(270) 555-0151",
    location: "Fort Campbell",
    readiness: 90,
    status: "available",
    nextAvailability: "Available now",
  },
  {
    id: "p-107",
    name: "SPC Rina Flores",
    rank: "SPC",
    roleTitle: "Intelligence Analyst",
    unit: "Task Force Bastion",
    squad: "S2 Cell",
    specialty: "All-source fusion",
    email: "rina.flores@army.demo",
    phone: "(910) 555-0170",
    location: "Fort Liberty",
    readiness: 98,
    status: "available",
    nextAvailability: "Available now",
  },
  {
    id: "p-108",
    name: "MAJ Marcus Hale",
    rank: "MAJ",
    roleTitle: "Executive Officer",
    unit: "Task Force Bastion",
    squad: "Command Group",
    specialty: "Operational command",
    email: "marcus.hale@army.demo",
    phone: "(910) 555-0127",
    location: "Fort Liberty",
    readiness: 97,
    status: "available",
    nextAvailability: "Available now",
  },
];

export const SECURITY_CONTROLS: SecurityControl[] = [
  {
    id: "s-1",
    title: "Signed session cookie with server verification",
    detail: "Portal sessions are issued only from server actions and verified again in secure route layouts.",
    status: "active",
    owner: "Platform",
  },
  {
    id: "s-2",
    title: "Optimistic route guard via Next.js Proxy",
    detail: "Unauthenticated traffic is redirected away from protected routes before page render.",
    status: "active",
    owner: "Edge",
  },
  {
    id: "s-3",
    title: "Security headers baseline",
    detail: "Frame denial, referrer hardening, permissions policy, and MIME sniff protection are enforced globally.",
    status: "active",
    owner: "Web",
  },
  {
    id: "s-4",
    title: "Microsoft Entra ID and CAC federation runway",
    detail: "The app is structured so the demo cookie flow can later be replaced with OIDC/SAML-backed identity.",
    status: "planned",
    owner: "Identity",
  },
];

export const AUDIT_EVENTS: AuditEvent[] = [
  {
    id: "e-1",
    title: "Supervisor sign-in",
    detail: "Successful credential sign-in for company operations role.",
    actor: "SSG Elena Ward",
    timestamp: "2026-04-15 11:42",
    severity: "neutral",
  },
  {
    id: "e-2",
    title: "High-risk leave package flagged",
    detail: "Request lr-1042 intersects the range density window and requires alternate coverage.",
    actor: "Policy engine",
    timestamp: "2026-04-15 11:48",
    severity: "watch",
  },
  {
    id: "e-3",
    title: "Session validation failed",
    detail: "Expired cookie rejected before portal render; user redirected to sign-in.",
    actor: "Proxy",
    timestamp: "2026-04-15 11:53",
    severity: "elevated",
  },
  {
    id: "e-4",
    title: "Command export generated",
    detail: "Leadership briefing packet rendered for battalion sync with staffing roll-up.",
    actor: "MAJ Marcus Hale",
    timestamp: "2026-04-15 12:07",
    severity: "neutral",
  },
];

export const REPORT_SERIES: ReportSeries[] = [
  {
    label: "Requests within 24h",
    value: 84,
    target: 90,
    summary: "Routing automation and cleaner briefs are keeping same-day decisions high.",
  },
  {
    label: "Coverage without cross-leveling",
    value: 71,
    target: 80,
    summary: "Weapons squad and medic coverage are the main drag on autonomous scheduling.",
  },
  {
    label: "Submission quality",
    value: 93,
    target: 95,
    summary: "Most packets arrive complete, but emergency contacts are still the most common miss.",
  },
  {
    label: "Leave conflict prevention",
    value: 89,
    target: 92,
    summary: "Conflict detection is working, but battalion freeze windows still need better pre-briefing.",
  },
];

export const FAQ_ITEMS: FaqItem[] = [
  {
    id: "f-1",
    question: "What changed in this portal compared with the original prototype?",
    answer:
      "The app now uses route-based navigation, server-issued sessions, protected portal routes, policy-aware request logic, and an operations-focused visual system.",
  },
  {
    id: "f-2",
    question: "Is this already integrated with a real identity provider?",
    answer:
      "Not yet. The current flow uses signed demo sessions so the UI and route architecture can be exercised safely while preserving a clean upgrade path to Microsoft Entra ID or CAC-backed federation.",
  },
  {
    id: "f-3",
    question: "How is leave risk scored?",
    answer:
      "The workbench checks request length, available balance, overlap with mission windows, and whether staffing-critical specialties are affected during protected dates.",
  },
  {
    id: "f-4",
    question: "Why are some requests routed to higher approval levels?",
    answer:
      "Requests that intersect freeze windows, reduce critical specialties, or exceed comfortable staffing buffers are escalated automatically to the command chain shown in the workbench.",
  },
];
